### ISSUE TITLE
Problems parsing DNS.log

### ISSUE THREAD

**Issue by Crypto-Cat** [elnappo/bro-log-parser#2]
Hi, When using this module on the DNS.log I get the following error:

```
entry_fields.append(bro_types[types[index]](field))
ValueError: invalid literal for float(): 5.000000,5.000000,5.000000
```

I think the issue is with the TTL field which can sometimes contain "5.000000,5.000000"

Not sure if you're actively maintaining this but if so, a fix would be appreciated :)

**Comment by elnappo** [comment]
Thanks for your bug report, the issue should be fixed with https://github.com/elnappo/bro-log-parser/commit/1706963aaae723b8a4694f9537094cbe97c3270e. Can you confirm that it's now working for you? I changed the method name to `parse_log_file` and `parse_log` now takes `TextIO`.

**Comment by Crypto-Cat** [comment]
Hi,

With the latest commit I get an error on line 7:

```
def _bro_types_mapping(separator_set: str) -> Dict:
                                        ^
SyntaxError: invalid syntax
```

Thanks,
Crypto

**Comment by elnappo** [comment]
Which python version are you using?

**Comment by Crypto-Cat** [comment]
Ah, I had been loading the bro-log-parse module into my python2 project, I'll try and port it over to python3. Thanks.

**Comment by Crypto-Cat** [comment]
Hi,

Using python3 now I get the following error:

```
bro-log-parser/brologparse.py", line 31, in parse_log
    separator = f.readline().rstrip("\n").split(" ")[1].encode('raw_unicode_escape').decode('unicode_escape')
AttributeError: 'str' object has no attribute 'readline'
```

Thanks,
Crypto

**Comment by elnappo** [comment]
Sorry for the inconvenience. I changed the method name to `parse_log_file` and `parse_log` now takes `TextIO`. If you change your code to use `parse_log_file` it should work.

**Comment by Crypto-Cat** [comment]
Ah, that's it working now. Cheers mate!
